# -*- coding: utf-8 -*-
"""camera_capture.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o-_nsKW92YQs-YmBAKUxkh7tQ3N1VOa5
"""

import cv2 as cv
import os
import numpy as np
from datetime import datetime

time = datetime.now()

time = int(round(time.timestamp()))

cascade = cv.CascadeClassifier('haarcascade_frontalface_alt2.xml')              #using haar cascade

                 #faces cascade data loaded 

#argument 0 is given to use the default camera of the laptop
camera = cv.VideoCapture(0)
#Now check if the camera object is created successfully
if not camera.isOpened():
    print("The Camera is not Opened....Exiting")
    exit()

#creating a list of lables "You could add as many you want"
Labels = ['angry', 'surprise','happy','sad','neutral','disgust','fear']
#Now create folders for each label to store images
for label in Labels:
    if not os.path.exists(label):
        os.mkdir(label)

for folder in Labels:
    #using count variable to name the images in the dataset.
    count = 0
    #Taking input to start the capturing
    print("Press 's' to start data collection for "+folder)
    userinput = input()
    if userinput != 's':
        print("Wrong Input..........")
        exit()
    #clicking 1 image for now   
    while count<20:
        #read returns two values one is the exit code and other is the frame
        status, frame = camera.read()
        #check if we get the frame or not
        if not status:
            print("Frame has not been captured..Exiting...")
            break
        #convert the image into gray format for fast caculation
        gray = cv.cvtColor(frame, cv.COLOR_BGR2GRAY)
        
        #display window with gray image
        cv.imshow("Video Window",gray)

        faces = cascade.detectMultiScale(gray, 1.1, 3)

        #sprint(faces)

        for x,y,w,h in faces:

            cropped = gray[y:y+h, x:x+w]
                       #crop the face part

            cropped = cv.resize(cropped, (48,48))               #resize into 48 by 48

            #recheking to ensure face is present in photo
            face_2 = cascade.detectMultiScale(cropped, 1.1, 3)
            # print(len(face_2))

            if len(face_2):
                cv.imwrite('../collecting_dataset_py/'+folder+'/img_'+str(time)+str(count)+'.png', cropped)
                count=count+1
                

        
        #to quite the display window press 'q'
        if cv.waitKey(1) == ord('q'):
            break

        
# When everything done, release the capture
camera.release()
cv.destroyAllWindows()
